version: '3.9'

services:
  mysql:
    restart: always
    image: mysql:8.0.29
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    networks:
      - env-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=yisen-cai
      - MYSQL_DATABASE=base-env


  redis:
    restart: always
    image: redis:7.0.2
    container_name: redis
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    mem_limit: 96m
    networks:
      - env-network


  postgres:
    image: postgres:14.3-1
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - env-network


  mongo:
    image: mongo:5.0.9
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    networks:
      - env-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  mongo:
    driver: local
  kafka:
    driver: local

networks:
  env-network:
    driver: bridge