version: '3.9'

services:
  # kafka cluster
  kafka1:
    image: 'bitnami/kafka:3.2'
    ports:
      - '9091:9092'
    container_name: kafka1
    volumes:
      - ./kafka1/:/bitnami/kafka1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - env-network
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - KAFKA_ZOOKEEPER_USER=kafka
      # - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      # - KAFKA_CLIENT_USERS=user
      # - KAFKA_CLIENT_PASSWORDS=password
      # - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123
      # - KAFKA_TLS_TYPE=JKS # or PEM

  kafka2:
    image: 'bitnami/kafka:3.2'
    ports:
      - '9092:9092'
    container_name: kafka2
    volumes:
      - ./kafka2/:/bitnami/kafka2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - env-network
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  
  kafka3:
    image: 'bitnami/kafka:3.2'
    ports:
      - '9093:9092'
    container_name: kafka3
    volumes:
      - ./kafka3/:/bitnami/kafka3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - env-network
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

volumes:
  mysql:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  mongo:
    driver: local
  kafka:
    driver: local

networks:
  env-network:
    driver: bridge