version: '3.9'

services:
  # zookeeper cluster
  zoo1:
    image: zookeeper:3.6.3
    restart: always
    hostname: zoo1
    container_name: zoo1
    ports:
      - 2181:2181
    networks:
      - env-network
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo2:
    image: zookeeper:3.6.3
    restart: always
    hostname: zoo2
    container_name: zoo2
    ports:
      - 2182:2181
    networks:
      - env-network
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181

  zoo3:
    image: zookeeper:3.6.3
    restart: always
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    networks:
      - env-network
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181



volumes:
  mysql:
    driver: local
  redis:
    driver: local
  postgres:
    driver: local
  mongo:
    driver: local
  kafka:
    driver: local

networks:
  env-network:
    driver: bridge